services:
  - type: web
    name: phishnet-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile.backend
    dockerContext: ./backend
    plan: free
    envVars:
      - key: VIRUSTOTAL_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false